name: CMake

on:
  push:
    branches:
      - '**'
    tags:
      - '*'
  pull_request:
    branches: [ main ]

jobs:
  build-macos:
    runs-on: macos-12

    steps:
    - uses: actions/checkout@v2

    - name: Set environment release variable
      if: startsWith(github.ref, 'refs/tags/')
      run: echo "BUILD_TYPE=Release" >> $GITHUB_ENV

    - name: Set environment debug variable
      if: false == startsWith(github.ref, 'refs/tags/')
      run: echo "BUILD_TYPE=Debug" >> $GITHUB_ENV

    - name: Checkout submodules
      run: git submodule update --init --recursive

    - name: Remove conflicting symlinks
      run: |
        rm /usr/local/bin/2to3 || true
        rm /usr/local/bin/idle3 || true
        rm /usr/local/bin/pydoc3 || true
        rm /usr/local/bin/python3 || true
        rm /usr/local/bin/python3-config || true

        rm /usr/local/bin/2to3-3.11 || true
        rm /usr/local/bin/idle3.11 || true
        rm /usr/local/bin/pydoc3.11 || true
        rm /usr/local/bin/python3.11 || true
        rm /usr/local/bin/python3.11-config || true

    - name: Install dependencies
      run: |
        brew update
        brew install libsamplerate aubio

    - name: Configure CMake
      run: cmake -B code/build -S code -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build code/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}
      run: | 
        cmake --build code/build --config ${{env.BUILD_TYPE}} --target validator
        ./code/scripts/vst3_validator_tests.sh ${{env.BUILD_TYPE}}

    - name: Prepare Archive
      working-directory: ${{github.workspace}}
      run: ./code/scripts/package_macos_artifacts.sh ${{env.BUILD_TYPE}}

    - name: Archive all applications
      uses: actions/upload-artifact@v2
      with:
        path: code/build/artifacts/

    - name: Create release
      uses: softprops/action-gh-release@v0.1.13
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: code/build/artifacts/*
