name: CMake

on:
  push:
    branches:
      - '**'
    tags:
      - '*'
  pull_request:
    branches: [ main ]

jobs:
  build-macos:
    runs-on: macos-11

    steps:
    - uses: actions/checkout@v2

    - name: Set environment release variable
      if: startsWith(github.ref, 'refs/tags/')
      run: echo "BUILD_TYPE=Release" >> $GITHUB_ENV

    - name: Set environment debug variable
      if: false == startsWith(github.ref, 'refs/tags/')
      run: echo "BUILD_TYPE=Debug" >> $GITHUB_ENV

    - name: Checkout submodules
      run: git submodule update --init --recursive

    - name: Install dependencies
      run: |
        brew update
        brew install libsamplerate aubio

    - name: Configure CMake
      run: cmake -B code/build -S code -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build code/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/code/build
      run: ctest -C ${{env.BUILD_TYPE}}

    - name: Prepare Archive
      working-directory: ${{github.workspace}}
      run: ./code/scripts/package_macos_artifacts.sh ${{env.BUILD_TYPE}}

    - name: Archive all applications
      uses: actions/upload-artifact@v2
      with:
        path: code/build/artifacts/

    - name: Create release
      uses: softprops/action-gh-release@v0.1.13
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: code/build/artifacts/*

  build-ubuntu:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set environment release variable
      if: startsWith(github.ref, 'refs/tags/')
      run: echo "BUILD_TYPE=Release" >> $GITHUB_ENV

    - name: Set environment debug variable
      if: false == startsWith(github.ref, 'refs/tags/')
      run: echo "BUILD_TYPE=Debug" >> $GITHUB_ENV

    - name: Checkout submodules
      run: git submodule update --init --recursive

    - name: Install dependencies
      run: |
         sudo apt update
         sudo apt install libasound2-dev libjack-jackd2-dev \
         ladspa-sdk \
         libcurl4-openssl-dev  \
         libfreetype6-dev \
         libx11-dev libxcomposite-dev libxcursor-dev libxcursor-dev libxext-dev libxinerama-dev libxrandr-dev libxrender-dev \
         libwebkit2gtk-4.0-dev libxcb-util-dev xcb-util-cursor \
         libglu1-mesa-dev mesa-common-dev
         sudo apt-get update
         sudo apt-get install libsamplerate-dev
         sudo apt-get install aubio-tools libaubio-dev libaubio-doc

    - name: Configure CMake
      run: cmake -B code/build -S code -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build code/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/code/build
      run: ctest -C ${{env.BUILD_TYPE}}

    - name: Prepare Archive
      working-directory: ${{github.workspace}}
      run: ./code/scripts/package_ubuntu_artifacts.sh ${{env.BUILD_TYPE}}

    - name: Tar Archive
      working-directory: ${{github.workspace}}/code/build
      run: tar -cvf kmswhdsp.tar artifacts

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        path: code/build/kmswhdsp.tar

    - name: Create release
      uses: softprops/action-gh-release@v0.1.13
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: code/build/kmswhdsp.tar
